name: Releases

on:
  push:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        artifactContentType: jar
        token: ${{ secrets.GITHUB_TOKEN }}
