name: Releases

on:
  push:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: |
        mvn clean compile package -pl Plugin -B --also-make
        mkdir dist
        mv Plugin/target/orebfuscator-*.jar ./dist
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        token: ${{ secrets.GITHUB_TOKEN }}
